AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Amplify deployment for Hiragana Flash Cards Next.js application'

Parameters:
  AppName:
    Type: String
    Default: 'hiragana-flash-cards'
    Description: 'Name of the Amplify application'
    
  Repository:
    Type: String
    Description: 'GitHub repository in format owner/repo-name'
    
  Branch:
    Type: String
    Default: 'main'
    Description: 'Git branch to deploy'
    
  GitHubToken:
    Type: String
    NoEcho: true
    Description: 'GitHub personal access token for repository access'

Resources:
  # IAM Role for Amplify
  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-amplify-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify

  # Amplify Application
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Repository: !Sub 'https://github.com/${Repository}'
      AccessToken: !Ref GitHubToken
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn
      Platform: WEB_COMPUTE
      
      # Build settings for Next.js
      BuildSpec: |
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci
                build:
                  commands:
                    - npm run build
              artifacts:
                baseDirectory: .next
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
                  - .next/cache/**/*
            appRoot: /
            
      # Environment variables
      EnvironmentVariables:
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: /
        - Name: _LIVE_UPDATES
          Value: '[{"name":"Next.js version","pkg":"next","type":"npm","version_run":"npx next --version"}]'

  # Branch for deployment
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref Branch
      EnableAutoBuild: true
      EnablePullRequestPreview: true
      
      # Build settings
      Framework: Next.js - SSG
      Stage: PRODUCTION

  # Domain (optional - uncomment and modify if you have a custom domain)
  # AmplifyDomain:
  #   Type: AWS::Amplify::Domain
  #   Properties:
  #     AppId: !GetAtt AmplifyApp.AppId
  #     DomainName: 'yourdomain.com' # Replace with your domain
  #     SubDomainSettings:
  #       - Prefix: ''
  #         BranchName: !GetAtt AmplifyBranch.BranchName

Outputs:
  AmplifyAppId:
    Description: 'Amplify App ID'
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppId'
      
  AmplifyAppUrl:
    Description: 'Amplify App URL'
    Value: !Sub 'https://${Branch}.${AmplifyApp.AppId}.amplifyapp.com'
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppUrl'
      
  AmplifyConsoleUrl:
    Description: 'Amplify Console URL'
    Value: !Sub 'https://console.aws.amazon.com/amplify/home#/${AmplifyApp.AppId}'
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyConsoleUrl'